# Generated by Django 2.2.2 on 2019-06-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=250)),
                ('tdepartment', models.EmailField(max_length=250)),
                ('tcourse', models.CharField(max_length=250)),
                ('tsubject', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
    ]
